theme: jekyll-theme-dinky
title: Teoría Estadística
description: Curso del tercer año del plan de estudios del bachillerato en Estadística. Utiliza la teoría de la probabilidad en espacios discretos y continuos, y el cálculo diferencial e integral, para desarrollar los fundamentos matemáticos de la inferencia estadística clásica, y ofrecer una introducción a la inferencia Bayesiana.
